openapi: 3.0.0
info:
  title: Documentación de la API de Pacientes
  description: Documentación de los endpoints relacionados con la gestión de pacientes.
  version: 1.0.0
tags:
  - name: patients
    description: Endpoints relacionados con la gestión de pacientes
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /patients:
    post:
      summary: Crear paciente
      description: Crea un nuevo registro de paciente.
      tags:
        - patients
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: // Define las propiedades del paciente aquí.

      responses:
        '201':
          description: Paciente creado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties: // Define las propiedades del paciente aquí.

    get:
      summary: Obtener todos los pacientes
      description: Obtiene una lista de todos los pacientes registrados.
      tags:
        - patients
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de pacientes obtenida exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties: // Define las propiedades del paciente aquí.

  /patients/{id}:
    get:
      summary: Obtener paciente por ID
      description: Obtiene la información de un paciente por su ID.
      tags:
        - patients
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID del paciente a obtener.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Información del paciente obtenida exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties: // Define las propiedades del paciente aquí.

    put:
      summary: Actualizar paciente
      description: Actualiza la información de un paciente existente.
      tags:
        - patients
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID del paciente a actualizar.
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: // Define las propiedades del paciente aquí.

      responses:
        '200':
          description: Información del paciente actualizada exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties: // Define las propiedades del paciente aquí.

    delete:
      summary: Eliminar paciente
      description: Elimina un paciente existente.
      tags:
        - patients
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID del paciente a eliminar.
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Paciente eliminado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
