swagger: "2.0"
info:
  title: Gestión de Citas Médicas
  description: API para la gestión de especialistas médicos en el sistema de citas médicas.
  version: 1.0.0
basePath: /api
tags:
  - name: Specialists
    description: Operaciones relacionadas con los especialistas médicos
securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header
paths:
  /Specialist:
    post:
      tags:
        - Specialists
      summary: Crear un nuevo especialista
      description: Crea un nuevo especialista en el sistema.
      parameters:
        - in: body
          name: body
          description: Datos del especialista a crear
          required: true
          schema:
            $ref: "#/definitions/SpecialistInput"
      responses:
        201:
          description: Especialista creado correctamente
        400:
          description: Datos de especialista inválidos
        401:
          description: No se proporcionó un token de autenticación
        403:
          description: Token de autenticación inválido
        500:
          description: Error interno del servidor
    get:
      tags:
        - Specialists
      summary: Obtener todos los especialistas
      description: Obtiene una lista de todos los especialistas en el sistema.
      responses:
        200:
          description: Lista de especialistas obtenida correctamente
          schema:
            type: array
            items:
              $ref: "#/definitions/Specialist"
        401:
          description: No se proporcionó un token de autenticación
        403:
          description: Token de autenticación inválido
        500:
          description: Error interno del servidor
  /Specialist/{id}:
    get:
      tags:
        - Specialists
      summary: Obtener información de un especialista por ID
      description: Obtiene la información detallada de un especialista por su ID.
      parameters:
        - in: path
          name: id
          description: ID del especialista a consultar
          required: true
          type: string
      responses:
        200:
          description: Información del especialista obtenida correctamente
          schema:
            $ref: "#/definitions/Specialist"
        404:
          description: Especialista no encontrado
        401:
          description: No se proporcionó un token de autenticación
        403:
          description: Token de autenticación inválido
        500:
          description: Error interno del servidor
    put:
      tags:
        - Specialists
      summary: Actualizar información de un especialista por ID
      description: Actualiza la información de un especialista existente por su ID.
      parameters:
        - in: path
          name: id
          description: ID del especialista a actualizar
          required: true
          type: string
        - in: body
          name: body
          description: Datos actualizados del especialista
          required: true
          schema:
            $ref: "#/definitions/SpecialistInput"
      responses:
        200:
          description: Especialista actualizado correctamente
        404:
          description: Especialista no encontrado
        401:
          description: No se proporcionó un token de autenticación
        403:
          description: Token de autenticación inválido
        500:
          description: Error interno del servidor
    delete:
      tags:
        - Specialists
      summary: Eliminar un especialista por ID
      description: Elimina un especialista existente por su ID.
      parameters:
        - in: path
          name: id
          description: ID del especialista a eliminar
          required: true
          type: string
      responses:
        200:
          description: Especialista eliminado correctamente
        404:
          description: Especialista no encontrado
        401:
          description: No se proporcionó un token de autenticación
        403:
          description: Token de autenticación inválido
        500:
          description: Error interno del servidor
definitions:
  Specialist:
    type: object
    properties:
      id:
        type: string
        example: "60f9a6a58610200015d96106"
      firstName:
        type: string
        example: "John"
      lastName:
        type: string
        example: "Doe"
      registrationNumber:
        type: string
        example: "123456789"
      address:
        type: object
        properties:
          street:
            type: string
            example: "123 Main St"
          city:
            type: string
            example: "New York"
          postalCode:
            type: string
            example: "10001"
      phoneNumber:
        type: string
        example: "123-456-7890"
      email:
        type: string
        format: email
        example: "john.doe@example.com"
  SpecialistInput:
    type: object
