openapi: 3.0.0
info:
  title: Documentación de la API de Citas Médicas
  description: Documentación de los endpoints relacionados con la gestión de citas médicas.
  version: 1.0.0
tags:
  - name: appointments
    description: Endpoints relacionados con la gestión de citas médicas
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /appointments:
    post:
      summary: Crear cita médica
      description: Crea una nueva cita médica.
      tags:
        - appointments
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                patientId:
                  type: integer
                  description: ID del paciente asociado a la cita médica.
                specialistId:
                  type: integer
                  description: ID del especialista asociado a la cita médica.
                

      responses:
        '201':
          description: Cita médica creada exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  // Define las propiedades de la cita médica aquí.

    get:
      summary: Obtener todas las citas médicas
      description: Obtiene una lista de todas las citas médicas registradas.
      tags:
        - appointments
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de citas médicas obtenida exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    // Define las propiedades de la cita médica aquí.

  /appointments/{id}:
    get:
      summary: Obtener cita médica por ID
      description: Obtiene la información de una cita médica por su ID.
      tags:
        - appointments
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID de la cita médica a obtener.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Información de la cita médica obtenida exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  // Define las propiedades de la cita médica aquí.

    put:
      summary: Actualizar cita médica por ID
      description: Actualiza la información de una cita médica existente por su ID.
      tags:
        - appointments
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID de la cita médica a actualizar.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                // Define las propiedades de la cita médica aquí.

      responses:
        '200':
          description: Información de la cita médica actualizada exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  // Define las propiedades de la cita médica aquí.

    delete:
      summary: Cancelar cita médica por ID
      description: Cancela una cita médica existente por su ID.
      tags:
        - appointments
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID de la cita médica a cancelar.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cita médica cancelada exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

    put:
      summary: Confirmar cita médica por ID
      description: Confirma una cita médica existente por su ID.
      tags:
        - appointments
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          description: ID de la cita médica a confirmar.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Cita médica confirmada exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  // Define las propiedades de la cita médica aquí.
